name: novaos-gypsy-cove
services:
  - name: gypsy-cove
    image:
      registry: ghcr.io
      repository: nacktgem/novaos-gypsy-cove
      tag: latest
    run_command: node server.js
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD
        value: production
      - key: CORE_API_BASE
        scope: RUN_AND_BUILD
        value: https://api.blackrosecollective.studio
      - key: CORE_API_URL
        scope: RUN_AND_BUILD
        value: https://api.blackrosecollective.studio
      - key: ECHO_WS
        scope: RUN_AND_BUILD
        value: wss://echo.blackrosecollective.studio/ws
      - key: SITE_URL
        scope: RUN_AND_BUILD
        value: https://gypsy-cove.xyz
      - key: NOVA_CONSOLE_BASE_URL
        scope: RUN_AND_BUILD
        value: https://novaos.blackrosecollective.studio
      - key: BRC_DOMAIN
        scope: RUN_AND_BUILD
        value: blackrosecollective.studio
    routes:
      - path: /
        domain: gypsy-cove.xyz
    health_check:
      protocol: HTTP
      path: /
      port: 3000
