version: '3.9'
services:
  core-api:
    build:
      context: .
      dockerfile: services/core-api/Dockerfile
    profiles: ['prod']
    env_file: [.env]
    volumes:
      - ./logs:/app/logs
    ports:
      - '8760:8760'
  echo:
    build:
      context: .
      dockerfile: services/echo/Dockerfile
    profiles: ['prod']
    env_file: [.env]
    volumes:
      - ./logs:/app/logs
    ports:
      - '8765:8765'
  gypsy-cove:
    build:
      context: .
      dockerfile: apps/gypsy-cove/Dockerfile
    profiles: ['prod']
    env_file: [.env]
    ports:
      - '3000:3000'
  nova-console:
    build:
      context: .
      dockerfile: apps/nova-console/Dockerfile
    profiles: ['prod']
    env_file: [.env]
    ports:
      - '3001:3001'
  web-shell:
    build:
      context: .
      dockerfile: apps/web-shell/Dockerfile
    profiles: ['prod']
    env_file: [.env]
    ports:
      - '3002:3002'
