[project]
name = "echo"
version = "0.1.0"
dependencies = [
  "fastapi==0.116.1",
  "uvicorn==0.35.0",
  "redis==5.0.4",
  "httpx==0.27.2",
  "pyjwt==2.9.0"
]
[project.optional-dependencies]
dev = ["pytest==8.4.1", "pytest-asyncio==0.23.5", "fakeredis==2.23.2", "rsa==4.9"]
