name: ci
on: [push, pull_request]
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22', cache: 'pnpm' }
      - run: corepack enable
      - run: pnpm -v
      - run: pnpm -w install --frozen-lockfile
      - run: pnpm -r lint
      - run: pnpm -r build
      - run: pnpm -r test
      - run: pnpm dlx license-checker-rseidelsohn --summary
<<<<<<< HEAD
      - run: |
          if command -v syft >/dev/null 2>&1; then
            syft dir:. -o json > sbom.json
          else
            echo 'syft not installed'
          fi
=======
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOM
        run: |
          mkdir -p .sbom
          syft dir:. -o syft-json > .sbom/project-sbom.json || { echo "SBOM generation failed"; exit 1; }
          if [ ! -s .sbom/project-sbom.json ]; then
            echo "SBOM file is empty or not generated"; exit 1
          fi
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: project-sbom
          path: .sbom/project-sbom.json
>>>>>>> origin/main
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip uv
      - run: uv venv
      - run: uv pip install -r requirements-dev.txt || true
      - run: pytest agents/glitch/tests core/tests -q
      - run: |
          cd services/core-api
          alembic upgrade head --sql >/dev/null
          heads=$(alembic heads | wc -l)
          if [ "$heads" -ne 1 ]; then
            echo 'multiple migration heads'
            exit 1
          fi
          alembic current
