name: CI

on: [push, pull_request]

jobs:
  core-api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: nova
          POSTGRES_PASSWORD: nova
          POSTGRES_DB: nova
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U nova -d nova" --health-interval=5s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7
        ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e services/core-api[dev]
      - working-directory: services/core-api
        run: |
          inv db.init
          inv db.upgrade
          inv db.seed
          pytest -q

  echo:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e services/echo[dev]
      - working-directory: services/echo
        run: pytest -q

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r build
      - run: pnpm -r lint
      - run: pnpm -r test
