name: Build and push core-api

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (pnpm)
        run: pnpm install -r

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: secrets.GHCR_PAT
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build core-api image
        uses: docker/build-push-action@v4
        with:
          context: ./services/core-api
          file: ./services/core-api/Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/novaos-core-api:latest

      - name: Push (placeholder)
        if: secrets.GHCR_PAT
        uses: docker/build-push-action@v4
        with:
          context: ./services/core-api
          file: ./services/core-api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/novaos-core-api:latest
