name: Fetch models

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  fetch-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
      - name: Fetch models
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          python3 scripts/fetch_models.py --token-env HF_API_TOKEN --yes
