name: Publish Agents

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agent: [nova, lyra, velora, glitch, echo, riven, audita]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push ${{ matrix.agent }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/dockerfiles/agent.${{ matrix.agent }}.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/novaos-agent-${{ matrix.agent }}:latest
            ghcr.io/${{ github.repository_owner }}/novaos-agent-${{ matrix.agent }}:${{ github.sha }}
          provenance: true
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max